../../src/package.sv        	
../../src/ff.sv         	
../../src/add.sv            	
../../src/alu.sv            	
../../src/control.sv        	
../../src/EX_Mem_Reg.sv     	
../../src/Forwarding_Unit.sv	
../../src/Hazard_Ctrl_Unit.sv
../../src/ID_EX_Reg.sv     
../../src/IF_ID_Reg.sv     
../../src/imm_gen.sv       
../../sram_32_1024_freepdk45/sram_32_1024_freepdk45.v        
../../src/Mem_WB_Reg.sv    
../../src/register_file.sv 
../../src/Cache_Branch.sv 
../../src/Branch_Fetch.sv 
../../src/FETCH.sv  		 
../../src/DECODE.sv  		 
../../src/EXECUTE.sv  		 
../../src/MEMORY_Stage.sv  		 
../../src/FSM.sv  		 
../../src/I_FSM.sv  		 
../../src/ICACHE.sv  		 
../../src/TOP_Entity.sv   
../../tb/testbench.sv

